---
name: osb-bosh-kafka
releases:
- name: osb-bosh-kafka
  version: latest
- name: osb-bosh-monitoring
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: true

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: zookeeper
  azs:
  - z1
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: 10GB
  networks:
  - name: default
  jobs:
  - name: zookeeper
    release: osb-bosh-kafka
  properties:
    zookeeper:
      config:
        autopurge_purge_interval: 24
        autopurge_snap_retain_count: 3
        cnx_timeout: 5
        election_algorithm: 3
        warning_threshold_ms: 1000
        global_outstanding_limit: 1000
        init_limit: 5
        leader_serves: "yes"
        max_client_connections: 60
        max_session_timeout: 40000
        min_session_timeout: 4000
        pre_allocation_size: 65536
        snap_count: 100000
        sync_enabled: true
        sync_limit: 2
        tick_time: 2000
        force_sync: "yes"

- name: kafka
  azs:
  - z1
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: 10GB
  networks:
  - name: default
  jobs:
  - name: kafka
    release: osb-bosh-kafka
  - name: status
    release: osb-bosh-kafka
  properties:
    kafka:
      security:
        setup_secure_client_connection: false
        admin_password: changeme
        ssl:
          certificate_authorities: changeme
          certificate: changeme
          key: changeme
      config:
        delete_topic: true
        offsets_topic_replication_factor: 1
        num_network_threads: 3
        num_io_threads: 8
        max_poll_interval: 5000
        socket_send_buffer_bytes: 102400
        socket_receive_buffer_bytes: 102400
        socket_request_max_bytes: 104857600
        num_partitions: 1
        num_recovery_threads_per_data_dir: 1
        log_retention_hours: 168
        log_retention_check_interval_ms: 300000
        log_segment_bytes: 1073741824

- name: kafka-smoke-test-runner
  lifecycle: errand
  instances: 1
  azs:
  - z1
  jobs:
  - name: kafka-smoke-test
    release: osb-bosh-kafka
  vm_type: default
  stemcell: default
  networks:
  - name: default
  properties: {}

