---
name: osb-bosh-kafka
releases:
- name: osb-bosh-kafka
  version: latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: true
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
instance_groups:
- name: zookeeper
  azs:
  - z1
  instances: 2
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks: [{name: service}]
  jobs:
  - name: zookeeper
    release: osb-bosh-kafka
    properties: {}
- name: kafka
  azs:
  - z1
  instances: 3
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks: [{name: service}]
  jobs:
  - name: kafka
    release: osb-bosh-kafka
    properties: {}
  - name: status
    release: osb-bosh-kafka
    properties: {}

- name: kafka-smoke-tests
  lifecycle: errand
  instances: 1
  azs:
  - z1
  jobs:
  - name: kafka-smoke-test
    release: osb-bosh-kafka
    properties: {}
  vm_type: default
  stemcell: default
  networks: [{name: service}]