---
name: osb-bosh-kafka
releases:
- name: osb-bosh-kafka
  version: latest
- name: bpm
  version: 0.2.0
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: true
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
instance_groups:
- name: osb-bosh-kafka
  azs:
  - az00
  instances: 1
  vm_type: small
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: kafka
    release: osb-bosh-kafka
    properties: {}
  - name: status
    release: osb-bosh-kafka
    properties: {}
- name: zookeper
  azs:
  - az00
  instances: 1
  vm_type: small
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: zookeeper
    release: osb-bosh-kafka
    properties: {}
- name: kafka-smoke-tests
  lifecycle: errand
  instances: 1
  azs:
  - az00
  jobs:
  - name: kafka-smoke-test
    release: osb-bosh-kafka
    properties: {}
  vm_type: nano
  stemcell: default
  networks: [{name: default}]
addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm