---
name: osb-bosh-mongodb

releases:
- name: osb-bosh-mongodb
  version: latest
- name: osb-bosh-monitoring
  version: latest
update:
  canaries: 1
  canary_watch_time: 15000-30000
  update_watch_time: 15000-30000
  max_in_flight: 2

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: mongodb
  instances: 1
  vm_type: small
  stemcell: default
  persistent_disk_type: 10GB
  azs:
  - z1
  networks:
  - name: service
  jobs:
  - name: mongodb3
    release: osb-bosh-mongodb
  - name: node_exporter
    release: osb-bosh-monitoring
  - name: mongodb_exporter
    release: osb-bosh-monitoring

- name: create-replset
  instances: 1
  lifecycle: errand
  vm_type: minimal
  stemcell: default
  azs:
  - z1
  networks:
  - name: service
  jobs:
  - name: create-replset
    release: osb-bosh-mongodb

- name: reconfigure-replset
  instances: 1
  lifecycle: errand
  vm_type: minimal
  stemcell: default
  azs:
  - z1
  networks:
  - name: service
  jobs:
  - name: reconfigure-replset
    release: osb-bosh-mongodb

properties:
  mongodb:
    auth:
      user: admin
      replica-set:
        keyfile: xav8/zX2tZlh8H8Fyuf3caLnYP0j9qzBzvgqs7voXK2ilVjHRfddKH2m6SfDV4JrmFhEjaOm1rEBrYxn5iyJMrqU2pvo30im3fTBNbtl9v14dGHN1wjzNS++Eh5S6zOip/ZRMtIm2d9A9MxQItVfjHukpFle8+7KpxHKIT99OyfPv0kmRkphW2bjOcbwPFrShrTlH8fCrCtseUdQyY1l4CnCvLxoRGgR3eDxRlZCA+ynNAqWWubx4jKv4m2CIV3HtZbdgsEd1xPg9XCEZq56224dnnAoOzxt+M5FkxfyyNCV6hEt+jJjL4SR5UFRDzxWypFa1E36a3K38yvOANwetAlxC68bR/v4vr5CDfkLUTPwRR2o1aekhIkt5aOmUFfujeDmRS+QxC0O19FTRTw1GWqoWQo01U+lFFYt5OtYe+KJHVS4JFsE8jJ1tYK8tPSwF9osdoCaJ28Ssy+kontt+tZAlbSLSZK/6HiHA8Oo95haAx1unGCWW1TTbiKkcCAmfkReyPgkzwpJW3/53o1h7g3jSohWqDalqWzCiLkeyFBGvgbLA/z32dS+/sBmJhPtf8EuaZyT7dALYzt8rflsj7uiq6khat0To+VVwemE7Vzk5srY1XdU5P0TtK1kaRib0wbPq1Aob46xkKAZBkD9iEbMLcBZTPn01gUErPHoRyjR+9Z08aofKCka5wSUpXcUgTQ+iu+tgfVvcgaunwWr/lCiFQUEP3aFWT+s5hWJwBkdB7JltpPVCKu9Pj3vqZjGX6r2Y/JihsPrCj1ysFvWm2XxQgLguU3RwD9JgQ2ax17KlZWAoQNJw1yoeRNBCqnwim1HDBIz6LyJqbI8qUC7RuRyiQV5Psg5ac1/FEJEkUYLcCPgffkwSHipfdJtEoRa/KTlow6dBwbdPpkz+HOWOI/rcT6LCSq0ByEUYyAB850f398E+E4peB/TVFDdT4y0872GUmUoisZ41bC6nlYdSnb9NVrz
    datadir: /var/vcap/store/mongodb3/
  mongodb_exporter:
    user: admin
